[package]
name = "wasm-envoy-proxy"
version = "0.1.0"
authors = ["David Illing"]
edition = "2024"


[lib]
crate-type = ["cdylib"]

[dependencies]
proxy-wasm = "0.2.2"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"
strip = "debuginfo"
