services:
  auth:
    build:
      context: ./auth
    volumes:
      - ./PotatoService.thrift:/app/PotatoService.thrift
    environment:
      - THRIFT_PATH=./PotatoService.thrift
    networks:
      - mesh
  envoy:
    image: envoyproxy/envoy:v1.33-latest
    hostname: envoy
    # entrypoint: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml -l trace
    ports:
      - "10000:10000"
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - ../target/wasm32-wasip1/release:/etc/envoy/proxy-wasm-plugins
    networks:
      - pod
      - mesh
  service:
    build:
      context: ./service
    networks:
      - pod
  client:
    build:
      context: ./client
    networks:
      - mesh
networks:
  pod: {}
  mesh: {}
